import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Book CRUD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className="py-10 px-10">{children}</div>
  )
}
